### ISSUE TITLE
Sends this error when I used it in my eval command to cache all the servers 

### ISSUE THREAD

**Issue by Jeydin21** [SourceBin/SourceBin#19]
```js
(node:18) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'json' of undefined
    at /app/node_modules/sourcebin_js/src/sourcebin-methods.js:107:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
app[service.1]: (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Jeydin21** [comment]
Why close .-.

**Comment by SebastiaanYN** [comment]
Issue is unrelated to SourceBin itself. Please open an issue in the repository of the API wrapper you're using instead.
